<a href="https://colab.research.google.com/github/tomasrodriguezr11/Programacion-MIAAD/blob/main/Practica19_266228.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Práctica 19 - Unidad 2: Datos Duplicados**
**Programación para analítica descriptiva y predictiva MIAAD**

*Realizada por: Tomás Eduardo Rodríguez Ramírez*

*Número de matrícula: 266228*

El objetivo de esta actividad es que los estudiantes pongan en práctica lo visto en el vídeo y en el notebook que se proporciona

# Instrucciones:
1. Descarga el archivo dirtydata.csv, proporcionado en esta tarea. También lo puedes encontrar en recursos.
2. Crea un notebook en colab y guarda el archivo csv  en tu drive.
3. Agrega secciones en el colab poniendo como título el nombre de cada ejercicio

**Ejercicio 01: Duplicidad Parcial Una columna: Contar y Filtrar los registros duplicados en Duration**
1. Carga el conjunto de datos dirty.csv y verifica que su carga sea correcta.
2. Cuenta la cantidad de registros duplicados utilizando solo la información de columna Duration e imprime
3. Utiliza value_counts() e imprime la cantidad de registros que hay por cada valor único.
4. Filtra los datos y obten los registros sin duplicados

**Ejercicio 02: Duplicidad Parcial Dos columnaa: Contar y Filtrar los registros duplicados en Pulse y MaxPulse**
1. Carga el conjunto de datos dirty.csv y verifica que su carga sea correcta.
2. Cuenta la cantidad de registros duplicados utilizando la información de las columnas Pulse y Maxpulse
3. Utiliza value_counts() e imprime la cantidad de registros que hay por cada valor único.
4. Filtra los datos y obten los registros cuando keep = 'last'

**Ejercicio 03: Duplicidad Total o Exacta: Contar y Filtrar los registros duplicados**
1. Carga el conjunto de datos dirty.csv y verifica que su carga sea correcta.
2. Cuenta la cantidad de registros duplicados exactos (todas las columnas)
3. Utiliza sum() e imprime la cantidad de registros con duplicidad exacta
4. Filtra los datos y obten los registros cuando keep = 'last'

**Ejercicio 04: Cálculo de la media con duplicados y sin duplicados**
1. Carga el conjunto de datos dirty.csv y verifica que su carga sea correcta.
2. Calcula e imprime la media de las columnas Pulse y MaxPulse
3. Identifica los valores duplicados en las columnas Pulse y MaxPulse (Duplicidad Parcial) y elimina los registro repetidos. Quédate con las últimas ocurrencias
4. Utiliza el conjunto anterior sin datos duplicados (recuerda que solo quedaron las últimas ocurrencias de los datos) y calcula la media de las columnas Pulse y MaxPulse

Sube un archivo txt que contenga la liga a tu notebook

# **Ejercicio 01: Duplicidad Parcial Una columna: Contar y Filtrar los registros duplicados en Duration**

In [18]:
# Carga de liberías y conjunto de datos
import pandas as pd

dataset="drive/MyDrive/ProgramacionMIAAD/dirtydata.csv"
df = pd.read_csv(dataset)
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [19]:
# Conteo de registros duplicados usando solo la columna Duration
duplicados_duration = df.duplicated(subset=['Duration']).sum()
print("Cantidad de registros duplicados en Duration:", duplicados_duration)

Cantidad de registros duplicados en Duration: 28

In [20]:
# Cantidad de registros que hay por cada valor único con value_counts
print("\nConteo de valores únicos en Duration:")
print(df['Duration'].value_counts())

Conteo de valores únicos en Duration:
Duration
60     24
45      6
450     1
30      1
Name: count, dtype: int64

In [21]:
# Se filtran los registros sin duplicados
df_sin_dup_duration = df.drop_duplicates(subset=['Duration'])

print("\nDatos sin duplicados en Duration:")
df_sin_dup_duration

Datos sin duplicados en Duration:

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
3        45  '2020/12/04'    109       175     282.4
7       450  '2020/12/08'    104       134     253.3
8        30  '2020/12/09'    109       133     195.1

# **Ejercicio 02: Duplicidad Parcial Dos columnaa: Contar y Filtrar los registros duplicados en Pulse y MaxPulse**

In [24]:
# Conteo de registros duplicados de las columnas Pulse y Maxpulse
duplicados_pulse = df.duplicated(subset=['Pulse', 'Maxpulse']).sum()
print("Cantidad de registros duplicados en Pulse y Maxpulse:", duplicados_pulse)

Cantidad de registros duplicados en Pulse y Maxpulse: 3

In [26]:
# Cantidad de registros que hay por cada valor único usando value_counts()
print("\nConteo de combinaciones Pulse - Maxpulse:")
print(df.value_counts(subset=['Pulse', 'Maxpulse']))

Conteo de combinaciones Pulse - Maxpulse:
Pulse  Maxpulse
100    120         4
92     115         1
       118         1
97     125         1
90     112         1
98     120         1
       123         1
       124         1
100    119         1
       132         1
102    126         1
       127         1
       129         1
103    123         1
       132         1
       135         1
       147         1
104    132         1
       134         1
105    132         1
106    128         1
108    131         1
109    133         1
       175         1
110    130         1
       136         1
117    145         1
       148         1
130    101         1
Name: count, dtype: int64

In [28]:
# Se filtran los datos y se obtiene los registros cuando keep = 'last'
df_sin_dup_pulse = df.drop_duplicates(subset=['Pulse', 'Maxpulse'], keep='last')

print("\nDatos sin duplicados (conservando última ocurrencia):")
print(df_sin_dup_pulse)

Datos sin duplicados (conservando última ocurrencia):
    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

# **Ejercicio 03: Duplicidad Total o Exacta: Contar y Filtrar los registros duplicados**

In [30]:
# Cantidad de registros duplicados exactos (todas las columnas) utilizando sum()
duplicados_exactos = df.duplicated().sum()

print("Cantidad de registros con duplicidad exacta:", duplicados_exactos)

Cantidad de registros con duplicidad exacta: 1

In [31]:
# Filtra los datos y obten los registros cuando keep = 'last'
df_sin_dup_exactos = df.drop_duplicates(keep='last')

print("\nDatos sin duplicados exactos:")
print(df_sin_dup_exactos)

Datos sin duplicados exactos:
    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

# **Ejercicio 04: Cálculo de la media con duplicados y sin duplicados**

In [32]:
# Cálculo de la media de las columnas Pulse y Maxpulse
media_con_dup = df[['Pulse', 'Maxpulse']].mean()
print("\nMedia con duplicados:")
print(media_con_dup)

Media con duplicados:
Pulse       103.5
Maxpulse    128.5
dtype: float64

In [34]:
# Identificación de valores duplicados en las columnas Pulse y Maxpulse (Duplicidad Parcial) y eliminación de registros repetidos (quedándose con las últimas ocurrencias)
df_sin_dup = df.drop_duplicates(subset=['Pulse', 'Maxpulse'], keep='last')
df_sin_dup

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [36]:
# Cálculo de la media de las columnas Pulse y Maxpulse utilizando el conjunto anterior sin datos duplicados (donde solo quedaron las últimas ocurrencias de los datos)
media_sin_dup = df_sin_dup[['Pulse', 'Maxpulse']].mean()

print("\nMedia sin duplicados:")
print(media_sin_dup)

Media sin duplicados:
Pulse       103.862069
Maxpulse    129.379310
dtype: float64